/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule DictionaryComponent_word.graphql
 * @generated SignedSource<<66f6fe790f0ff8747340f88e7d5bb91b>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type DictionaryComponent_word = {
  id: string;
  definition?: ?any;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "DictionaryComponent_word",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "WordDefinition",
      "name": "definition",
      "plural": false,
      "selections": [
        {
          "kind": "FragmentSpread",
          "name": "DictionaryComponent_definition",
          "args": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Word"
};

module.exports = fragment;
