/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule DictionaryComponent_definition.graphql
 * @generated SignedSource<<8c5c245769f83d6d7a12053cb2b78fd1>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type DictionaryComponent_definition = {
  text?: ?string;
  image?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "DictionaryComponent_definition",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "text",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "image",
      "storageKey": null
    }
  ],
  "type": "WordDefinition"
};

module.exports = fragment;
